language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master
    - /^\d+\.\d+$/

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.4
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: nightly

before_install:
  - composer self-update

install: composer update $COMPOSER_FLAGS

script: ./phpunit
